### PR TITLE
Support analysing log files from other machines

### PR DESCRIPTION
**Pull request by daverigby**
This series of commits adds support for analysing log files from a different machine to the one oom-investigate.py is running on.

Specifically, it allows running the script on macOS against a log file generated by dmesg from CentOS 7.

### CODE REVIEW

**Comment by LukeShirnia** [comment]
Hey @daverigby, apologies for the obscenely late response.

I've raised a pull request here https://github.com/LukeShirnia/out-of-memory/pull/26
This PR is a rewrite of the script and includes the ability to check journald, dmesg and files, as well as reducing the memory footprint.
I've attempted to make it run on most Unix/Linux based OS, including macOS.
If you're still using this script, please could you test and let me know if you have any issues.
If you do have issues, let me know what's caused the issue, with any offending log lines and I'll get on making it compatible.
The PR isn't finished but it's in a fairly good working state now. I haven't added the ability to read from "pages RAM" to determine the system RAM yet, but I'll look into adding that soon. As the script is python 2.7-3.9 compatible, I've left the shebang as "#!/usr/bin/env python"

Thanks

**Comment by daverigby** [comment]
Thanks Luke - I'll take a look and test with some logs I have locally later this week.

**Comment by LukeShirnia** [comment]
Hi @daverigby hope you're well. I see you added a new commit here recently which prompted me to re-visit my PR https://github.com/LukeShirnia/out-of-memory/pull/26

I've added some testing to which should help expand the supported platforms and test a lot better in the future.

I've not made many changes to the script since last year but will re-visit it soon. If you're still using this script regularly would be able to take a look at https://github.com/LukeShirnia/out-of-memory/pull/26 and let me know if it's suitable for your needs please? My main concern is making sure all functionality is ported over correctly. I'm not in a position where I use this frequently any more so I'm slightly concerned I might have missed something.

The aim is to get a lot more verbose testing for log files/regex/systems etc. in the near future.

If you don't have time, please don't worry. I will however be looking to merge my PR into the main branch soon.

**Comment by LukeShirnia** [comment]
Hey @daverigby, I haven't heard back from you in a while but my v2 re-write was merged a while back. Hopefully this resolves your issue here. I'll close this for now but please do raise an issue if you have any trouble with the new version.

**Pull request closed without merging**
